"""
Django settings for ALJE_PROJECT project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
DEBUG = os.environ.get("DEBUG", "True") == "True"
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'ALJE_APP',
    'New_Outbound_App',
    'Location_Map_App',
    'Inbound_App',
    'rest_framework',
]

# MIDDLEWARE = [
#     'ALJE_APP.middleware.CustomCorsMiddleware',
#     'Location_Map_App.middleware.SingleSessionMiddleware', # Custom middleware for single session

#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
MIDDLEWARE = [
    'ALJE_APP.middleware.CustomCorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # ✅ Auth middleware MUST come first
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    # ✅ Your middleware AFTER auth
    'Location_Map_App.middleware.SingleSessionMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'ALJE_PROJECT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ALJE_PROJECT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases



# Database
# DATABASES = {
#     "default": {
#         "ENGINE": "mssql",
#         "NAME": os.environ.get("MSSQL_DB"),
#         "USER": os.environ.get("MSSQL_USER"),
#         "PASSWORD": os.environ.get("MSSQL_PASSWORD"),
#         "CONN_MAX_AGE": 600, # Keep connections alive for 10 minutes
#         "HOST": os.environ.get("MSSQL_HOST"),
#         "PORT": os.environ.get("MSSQL_PORT", ""),
#         "OPTIONS": {
#             "driver": "ODBC Driver 17 for SQL Server",
#             "trusted_connection": "yes",
#         },
#     }
# }
# Database
DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": os.environ.get("MSSQL_DB"),
        "USER": os.environ.get("MSSQL_USER"),
        "PASSWORD": os.environ.get("MSSQL_PASSWORD"),
        "HOST": os.environ.get("MSSQL_HOST"),
        "PORT": os.environ.get("MSSQL_PORT", ""),
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            "trusted_connection": "yes",

        },
    },

    "Inbound_db": {
        "ENGINE": "mssql",
        "NAME": os.environ.get("MSSQL_DB_2"),
        "USER": os.environ.get("MSSQL_USER_2"),
        "PASSWORD": os.environ.get("MSSQL_PASSWORD_2"),
        "HOST": os.environ.get("MSSQL_HOST_2"),
        "PORT": os.environ.get("MSSQL_PORT_2", ""),
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            "trusted_connection": "yes",

        },
    },
    "session_db": {
        "ENGINE": "mssql",
        "NAME": os.environ.get("MSSQL_DB_3"),
        "USER": os.environ.get("MSSQL_USER_3"),
        "PASSWORD": os.environ.get("MSSQL_PASSWORD_3"),
        "HOST": os.environ.get("MSSQL_HOST_3"),
        "PORT": os.environ.get("MSSQL_PORT_3", ""),
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            "trusted_connection": "yes",

        },
    },}

# <<<<<<< Updated upstream
# MSSQL_USER=BUYP_ALJE
# MSSQL_PASSWORD=12345
# MSSQL_HOST=103.48.180.245
# =======
APPEND_SLASH = False



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static and Media
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "ALJE_APP/static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 465))
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "True") == "True"
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "False") == "True"
EMAIL_HOST_USER = os.environ.get("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")


# MinIO / S3
MINIO_ENDPOINT = os.environ.get("MINIO_ENDPOINT")
MINIO_ACCESS_KEY = os.environ.get("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.environ.get("MINIO_SECRET_KEY")
MINIO_BUCKET_NAME = os.environ.get("MINIO_BUCKET_NAME")
MINIO_BUCKET_INTERNAL_DAMAGE  = os.environ.get("MINIO_BUCKET_INTERNAL_DAMAGE")
MINIO_INBOUND_CONTAINER_BUCKET_NAME  = os.environ.get("MINIO_INBOUND_CONTAINER_BUCKET_NAME")
MINIO_INBOUND_BUCKET_NAME  = os.environ.get("MINIO_INBOUND_BUCKET_NAME")
MINIO_INBOUND_PO_BUCKET_NAME  = os.environ.get("MINIO_INBOUND_PO_BUCKET_NAME")
MINIO_INBOUND_CONTAINER_QC_BUCKET_NAME  = os.environ.get("MINIO_INBOUND_CONTAINER_QC_BUCKET_NAME")
MINIO_INBOUND_PRODUCT_DAMAGE_BUCKET_NAME  = os.environ.get("MINIO_INBOUND_PRODUCT_DAMAGE_BUCKET_NAME")
MINIO_SECURE = os.environ.get("MINIO_SECURE", "False") == "True"


# CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["GET","POST","PUT","PATCH","DELETE","OPTIONS"]
CORS_ALLOW_HEADERS = ["Authorization","Content-Type","access-control-allow-origin","X-CSRFToken","x-session-token",]
    

# Sessions stored in DB
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # Session lasts 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire when browser closes
SESSION_SAVE_EVERY_REQUEST = True  # Extend session expiry on activity



# Cache - dummy (does nothing, used when Redis is not available)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    }
}

# DRF Throttling
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': ['rest_framework.throttling.UserRateThrottle'],
    'DEFAULT_THROTTLE_RATES': {
        'user': os.environ.get("DRF_USER_THROTTLE_RATE", "1000/minute"),
    },
}

# Use signed cookies for sessions to avoid needing the django_session database table
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
